version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: guilhermegiarola/node_app
    ports:
      - "3000:3000"
    environment:
      - DB=node_live_db
      - DB_USER=guilhermegiarola
      - DB_PASSWORD=password
      - DB_HOST=node_db
    depends_on:
      - node_db

  node_db:
    container_name: node_live_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=guilhermegiarola
      - POSTGRES_PASSWORD=password
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes: 
 node_db_data: {}
